name = "The Minehattan Project"
author = "LunarLoony"
version = "5.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5a1c438686093c9b8f714c83e2043687783c7348984c973f5215954b5a725e35"

[versions]
forge = "43.2.23"
minecraft = "1.19.2"
