
#General settings
[profiles]
	#A list of dimensions with associated city generation profiles (format <dimensionid>=<profilename>
	dimensionsWithProfiles = ["lostcities:lostcity=minehattan-project","overworld=minehattan-project"]

